### ISSUE TITLE
Example on how to use with Flutter

### ISSUE THREAD

**Issue by SEGVeenstra** [Hexer10/steam_login#1]
On pub.dev it has says this package is compatible with Flutter.
But I have no idea on how I can use this within my Flutter app.

Could you add an example for it?

**Comment by Hexer10** [comment]
Here is an example of what could you do:

```dart
import 'package:flutter/material.dart';
import 'package:flutter_webview_plugin/flutter_webview_plugin.dart';
import 'package:steam_login/steam_login.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Demo Steam Login',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String steamId;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Steam Login'),
      ),
      body: Center(
        child: Column(
          children: <Widget>[
            RaisedButton(
              child: Text('Login'),
              onPressed: () async {
                // Navigate to the login page.
                final result = await Navigator.of(context).push(
                    MaterialPageRoute(builder: (context) => SteamLogin()));
                setState(() {
                  steamId = result;
                });
              },
            ),
            Text('Steamid: $steamId'),
          ],
        ),
      ),
    );
  }
}

class SteamLogin extends StatelessWidget {
  final _webView = FlutterWebviewPlugin();

  @override
  Widget build(BuildContext context) {
    // Listen to the onUrlChanged events, and when we are ready to validate do so.
    _webView.onUrlChanged.listen((String url) async {
      var openId = OpenId.fromUri(Uri.parse(url));
      if (openId.mode == 'id_res') {
        await _webView.close();
        Navigator.of(context).pop(openId.validate());
      }
    });

    var openId = OpenId.raw('https://myapp', 'https://myapp/', null);
    return WebviewScaffold(
        url: openId.authUrl().toString(),
        appBar: AppBar(
          title: Text('Steam Login'),
        ));
  }
}
```

![FlutterSteam](https://user-images.githubusercontent.com/21113203/67023676-7ca69a80-f103-11e9-93db-248b78bb2e92.gif)

Note that there are for sure better ways to handle this, but as of now this should work ok.

You can replace the url in `OpenId.raw('https://myapp', 'https://myapp/', null)` with which value do you want, it will be the domain shown in the steam login page.

**Comment by Hexer10** [comment]
Be aware that you shouldn't make request to the steam api, since this would expose you steam api key, I suggest you to build you own server side app to do so.

**Comment by SEGVeenstra** [comment]
Thank you @Hexer10  for this great example!
I'll be trying it put soon!

**Comment by SEGVeenstra** [comment]
> Be aware that you shouldn't make request to the steam api, since this would expose you steam api key, I suggest you to build you own server side app to do so.

Thank you for the advice

**Comment by SEGVeenstra** [comment]
Is the result only the steamId?
I eventually want to use this login to auth with firebase so I should get a JWT somehow? Can I do this with this?

**Comment by H0neyCake** [comment]
Unfortunately your example does not work. When receiving the result, the following error appears: [https://imgur.com/a/IdVsvJq](https://imgur.com/a/IdVsvJq)

**Comment by SEGVeenstra** [comment]
> Unfortunately your example does not work. When receiving the result, the following error appears: https://imgur.com/a/IdVsvJq

I actually did get it to work back then. When does it show the error?

**Comment by H0neyCake** [comment]
When authentication has occurred and I should be returned to the main screen.

**Comment by DanielSmith1239** [comment]
This example doesn't seem to be working anymore with null safety.
